[package]
name = "rust-pong-tetra"
version = "0.1.0"
authors = ["Guilherme Torquato <guibaux@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6"